alioprints/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import urls as urls_accounts
from products import urls as urls_products
from home import urls as urls_home
from home.views import home
from cart import urls as urls_cart
from search import urls as urls_search
from checkout import urls as urls_checkout
from products.views import all_products
from django.views import static
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),
    url(r'^contact/', include(urls_home)),
    url(r'^accounts/', include(urls_accounts)),
    url(r'^products/', include(urls_products)),
    url(r'^cart/', include(urls_cart)),
    url(r'^checkout/', include(urls_checkout)),
    url(r'^search/', include(urls_search)),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),

]

cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart, remove_from_cart

urlpatterns = [
    url(r'^$', view_cart, name='view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name='add_to_cart'),
    url(r'^adjust/(?P<id>\d+)', adjust_cart, name='adjust_cart'),
    url(r'^remove/(?P<id>\d+)', remove_from_cart, name='remove_from_cart'),
]

home/urls.py
from django.conf.urls import url
from .views import home, contact


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^contact/$', contact, name='contact'),
]

home/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    query = forms.CharField(required=True, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Your name:"
        self.fields['email'].label = "Your email:"
        self.fields['query'].label = "How can we help?"

home/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.contrib import messages

# Create your views here.


def home(request):
    """A view that displays the index page"""
    return render(request, "home.html")


def contact(request):
    form_class = ContactForm

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            name = request.POST.get('name', '')
            email = request.POST.get('email', '')
            query = request.POST.get('query', '')

            template = get_template('contact_template.txt')
            context = {
                'name': name,
                'email': email,
                'query': query,
            }
            content = template.render(context)
            messages.error(request, "Thank you for your message. We will be in touch soon!")
            email = EmailMessage("New contact form submission", content, "Alio Prints" + '', ['alioprints@gmail.com'], headers={'Reply-To': email})
            email.send()
            return redirect('contact')

    return render(request, 'contact.html', {'form': form_class,})

home/templates/contact.html
<!DOCTYPE html>
<title>Contact</title>
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid background-container">
<!--CONTACT FORM-->
   <section class="contact">
      <div class="container-fluid">
      <h2>Get in touch</h2>
         <div class="row">
         <div class="col-12">
            <p>Send us a message</p>
            <div>
                <form id="myform" role="form" action="" method="post">
                  {% csrf_token %}
                    <input class="form-control" type="text" name="name" required="" id="id_name" placeholder="Your Name:">
                   <input class="form-control" type="email" name="email" required="" id="id_email" placeholder="Your Email:">
                    <textarea class="form-control" name="query" cols="40" rows="10" required="" id="id_query" placeholder="How can we help?"></textarea>
                  <div class="form-row text-center"><div class="col-12">
                     <button class="btn btn-success center-block" type="submit">Submit</button></div>
                  </div>
               </form>
               </div>
                 </div>
         </div>
      </div>
   </section>
</div>
{% endblock %}

home/templates/home.html
<!DOCTYPE html>
<title>Home</title>
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap_tags %}
{% block head_js %}
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container-fluid background-container">
   <!--SECTION ONE-->
   <section>
      <div class="jumbotron parallaxone">
         <div class="bg-dark">
            <h2>Welcome to Alio Prints!</h2>
            <br> 
            <p> Let's create something beautiful!</p>
         </div>
      </div>
   </section>
   <!--SECTION TWO-->
   <section class="parallaxtwo">
      <div class="col-6 offset-6">
         <h2>What we do...</h2>
         <p>We create personalised prints for all occasions! <br> New additions, birthdays, anniversarys and everything in between!</p>
         <div>
            <a target="_blank" href="{% url 'gallery' %}"><button class="btn btn-success viewgallery">View Gallery</button></a>
         </div>
      </div>
   </section>
   <!--SECTION THREE-->
   <section>
      <div class="parallaxthree">
         <div class="col-xs-8 col-sm-12 col-md-12 col-lg-12">
            <h2>How do we do it?</h2>
            <p><i class="fa fa-cart-plus" aria-hidden="true"></i>Choose your favourite prints and add to cart.<br> <i class="fa fa-pencil-square-o" aria-hidden="true"></i>Add the information you would like in your print to 'print details' in the checkout form. <br><i class="fa fa-paper-plane-o" aria-hidden="true"></i>Once your proof is signed off, your personalised print will be shipped within 7 working days!!</p>
            <div>
               <a target="_blank" href="{% url 'contact' %}"><button class="btn btn-success getintouch">Get in Touch</button></a>
            </div>
         </div>
      </div>
   </section>
   <!--SECTION FOUR-->
   <section class="parallaxfour">
      <div>
         <h2>Some of our bestsellers...</h2>
         <div class="container photo-gallery">
            <div class="col-md-12">
               <div class="well">
                  <div id="myCarousel" class="carousel slide">
                     <!-- CAROUSEL FOR LARGE SCREENS -->
                     <div class="carousel-inner portfolio-images">
                        <div class="item active">
                           <div class="row">
                              <div class="col-sm-3"><a href="{#}"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery1.png" alt="Image" class="img-responsive"></a>
                              </div>
                              <div class="col-sm-3"><a href="{#}"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery2.png" alt="Gallery2" class="img-responsive"></a>
                              </div>
                              <div class="col-sm-3"><a href="{#}"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery3.png" alt="Image" class="img-responsive"></a>
                              </div>
                              <div class="col-sm-3"><a href="{#}"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery4.png" alt="Image" class="img-responsive"></a>
                              </div>
                           </div>
                        </div>
                        <!--/item-->
                        <div class="item">
                           <div class="row">
                              <div class="col-sm-3"><a href="{#}" class="thumbnail"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery5.png" alt="Image" class="img-responsive"></a>
                              </div>
                              <div class="col-sm-3"><a href="{#}" class="thumbnail"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery6.png" alt="Image" class="img-responsive"></a>
                              </div>
                              <div class="col-sm-3"><a href="{#}" class="thumbnail"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery7.png" alt="Image" class="img-responsive"></a>
                              </div>
                              <div class="col-sm-3"><a href="{#}" class="thumbnail"><img src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery8.png" alt="Image" class="img-responsive"></a>
                              </div>
                           </div>
                        </div>
                     </div>
                     <!--/carousel-inner--> 
                     <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                     <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!--CAROUSEL FOR SMALL SCREENS-->
      <div class="container sml-carousel">
         <div class="row">
            <div class="col-8 offset-2">
               <div class="carousel slide carousel" id="carouselcontrols" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <img class="d-block w-100" src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery1.png" alt="gallery1">
                     </div>
                     <div class="carousel-item">
                        <img class="d-block w-100" src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery2.png" alt="gallery2">
                     </div>
                     <div class="carousel-item">
                        <img class="d-block w-100" src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery3.png" alt="gallery3">
                     </div>
                     <div class="carousel-item">
                        <img class="d-block w-100" src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery3.png" alt="gallery4">
                     </div>
                     <div class="carousel-item">
                        <img class="d-block w-100" src="https://alioprints.s3-eu-west-1.amazonaws.com/media/images/gallery4.png" alt="gallery5">
                     </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselcontrols" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselcontrols" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                  </a>
               </div>
            </div>
         </div>
      </div>
   </section>
</div>
{% endblock %}